CREATE TABLE CARNATIC_LANGUAGE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LANG_KEY VARCHAR(5) NOT NULL,
    CANONICAL_NAME VARCHAR(50) NOT NULL,
    DISPLAY_NAME VARCHAR(50) NOT NULL
);
INSERT INTO CARNATIC_LANGUAGE (LANG_KEY, CANONICAL_NAME, DISPLAY_NAME) VALUES ('en', 'English', 'English');
INSERT INTO CARNATIC_LANGUAGE (LANG_KEY, CANONICAL_NAME, DISPLAY_NAME) VALUES ('ta', 'Tamil', 'தமிழ்');
INSERT INTO CARNATIC_LANGUAGE (LANG_KEY, CANONICAL_NAME, DISPLAY_NAME) VALUES ('te', 'Telugu', 'తెలుగు');
INSERT INTO CARNATIC_LANGUAGE (LANG_KEY, CANONICAL_NAME, DISPLAY_NAME) VALUES ('kn', 'Kannada', 'ಕನ್ನಡ');
INSERT INTO CARNATIC_LANGUAGE (LANG_KEY, CANONICAL_NAME, DISPLAY_NAME) VALUES ('ml', 'Malayalam', 'മലയാളം');
