Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Sa'), (select id from carnatic_language where lang_key = 'ml'), 'സ', 'ഷഡ്ജം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ri1'), (select id from carnatic_language where lang_key = 'ml'), 'രി1', 'ശുദ്ധ ഋഷഭം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ri2'), (select id from carnatic_language where lang_key = 'ml'), 'രി2', 'ചതുശ്രുതി ഋഷഭം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ri3'), (select id from carnatic_language where lang_key = 'ml'), 'രി3', 'ഷഡ്ശ്രുതി ഋഷഭം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ga3'), (select id from carnatic_language where lang_key = 'ml'), 'ഗ3', 'ശുദ്ധ ഗന്ധാരം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ga1'), (select id from carnatic_language where lang_key = 'ml'), 'ഗ1', 'സാധരണ ഗന്ധാരം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ga2'), (select id from carnatic_language where lang_key = 'ml'), 'ഗ2', 'അന്തര ഗന്ധാരം');
Insert into note_translation (note_id, language_id, note_name, note_full_name) values ((select id from note_meta_data where notation = 'Ma1'), (select id from carnatic_language where lang_key = 'ml'), 'മ1', 'ശുദ്ധ മധ്യമം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Ma2'), (select id from carnatic_language where lang_key = 'ml'), 'മ2', 'പ്രതി മധ്യമം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Pa'), (select id from carnatic_language where lang_key = 'ml'), 'പ', 'പഞ്ചമം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Dha1'), (select id from carnatic_language where lang_key = 'ml'), 'ധ1', 'ശുദ്ധ ധൈവതം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Dha2'), (select id from carnatic_language where lang_key = 'ml'), 'ധ2', 'ചതുശ്രുതി ധൈവതം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Dha3'), (select id from carnatic_language where lang_key = 'ml'), 'ധ3', 'ഷഡ്ശ്രുതി ധൈവതം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Ni3'), (select id from carnatic_language where lang_key = 'ml'), 'നി3', 'ശുദ്ധ നിഷാദം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Ni1'), (select id from carnatic_language where lang_key = 'ml'), 'നി1', 'കൈശികി നിഷാദം');
Insert into note_translation (note_id, language_id, note_name,note_full_name) values ((select id from note_meta_data where notation = 'Ni2'), (select id from carnatic_language where lang_key = 'ml'), 'നി2', 'കാക്കലി നിഷാദം');

